# Generated by Django 5.2.7 on 2026-05-15 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(choices=[('all_centres', 'All Centres'), ('centre_specific', 'Centre Specific')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.IntegerField(blank=True, null=True)),
                ('target_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.centre')),
            ],
        ),
    ]
