# Generated by Django 5.2.7 on 2025-11-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('exam_id', models.AutoField(db_column='exam_id', primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_date', models.DateField()),
                ('exam_start_time', models.TimeField()),
                ('exam_end_time', models.TimeField()),
                ('subject_code', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_type', models.CharField(choices=[('Regular', 'Regular'), ('Supplementary', 'Supplementary')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('centre', models.ForeignKey(blank=True, db_column='centre_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='management.centre')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='management.course')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_examinations', to='management.centre')),
            ],
            options={
                'db_table': 'examinations',
            },
        ),
    ]
