# Generated by Django 5.2.7 on 2025-10-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='centre',
            field=models.ForeignKey(blank=True, db_column='centre_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='management.centre'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='management.course'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_examinations', to='management.centre'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='exam_id',
            field=models.AutoField(db_column='exam_id', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinations.examination')),
            ],
        ),
    ]
