# Generated by Django 5.2.7 on 2026-02-21 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_examination_exam_fee'),
        ('students', '0005_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStudentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_course_registered', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='exam_registrations/photos/')),
                ('exam_fee_receipt', models.FileField(blank=True, null=True, upload_to='exam_registrations/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='examinations.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to='students.student')),
            ],
        ),
    ]
