# Generated by Django 5.2.7 on 2025-11-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_alter_examination_centre_alter_examination_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
