# Generated by Django 5.2.7 on 2025-11-09 06:43

from django.db import migrations, models
dependencies = [
    ('users', '0001_initial'),
]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('centre_id', models.AutoField(primary_key=True, serialize=False)),
                ('centre_code', models.CharField(max_length=10, unique=True)),
                ('centre_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('validity_start_date', models.DateField()),
                ('validity_end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'centres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('stream', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('mou_required', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
    ]
