# Generated by Django 5.2.7 on 2026-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
