# Generated by Django 5.2.7 on 2026-03-11 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('temporary_student_id', models.CharField(max_length=50, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('educational_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_path', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='students/payments/')),
                ('eligibility_proof', models.FileField(blank=True, null=True, upload_to='students/eligibility/')),
                ('aadhar_path', models.FileField(blank=True, null=True, upload_to='students/aadhar/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='management.centre')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='management.course')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
