# Generated by Django 5.2.7 on 2025-11-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Centre',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
