# Generated by Django 5.2.7 on 2026-02-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='students/payments/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
    ]
