# Generated by Django 5.2.7 on 2026-02-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_payment_proof_alter_student_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhar_path',
            field=models.FileField(blank=True, null=True, upload_to='students/aadhar/'),
        ),
        migrations.AddField(
            model_name='student',
            name='eligibility_proof',
            field=models.FileField(blank=True, null=True, upload_to='students/eligibility/'),
        ),
    ]
