# Generated by Django 5.2.7 on 2025-11-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user_role', models.CharField(choices=[('Admin', 'Admin'), ('Centre', 'Centre')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centre', models.ForeignKey(blank=True, db_column='centre_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='management.centre')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
